import path from "node:path";
import {pathToFileURL} from "node:url";
const runtimeModules=process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES;
if(!runtimeModules)throw new Error("CODEX_PRIMARY_RUNTIME_NODE_MODULES is required for browser smoke testing");
const {chromium}=await import(pathToFileURL(path.join(runtimeModules,"playwright/index.mjs")).href);
const file=pathToFileURL(path.resolve("dist/blind-spot-standalone.html")).href;
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on("pageerror",e=>errors.push(e.message));
await page.goto(file);await page.waitForTimeout(500);
if(!(await page.locator("#menu.active").isVisible()))throw new Error("Title menu did not render");
await page.click("#playBtn");
if(await page.locator(".level-card:not(:disabled)").count()!==1)throw new Error("Fresh save should unlock only level 1");
await page.click('.level-card[data-level="0"]');await page.waitForTimeout(200);
const initial=await page.evaluate(()=>window.__blindSpot.getState());
if(initial.camerasRemaining!==1||initial.shotsRemaining!==3)throw new Error("Level 1 state is invalid");
const box=await page.locator("#game").boundingBox();
const sx=box.x+190*box.width/1280,sy=box.y+535*box.height/720;
await page.mouse.move(sx,sy);await page.mouse.down();await page.mouse.move(sx-105,sy+45,{steps:8});await page.mouse.up();await page.waitForTimeout(250);
const fired=await page.evaluate(()=>window.__blindSpot.getState());
if(fired.shotsUsed!==1)throw new Error("Drag/release did not consume exactly one shot");
await page.evaluate(()=>window.__blindSpot.forceDisableAll());await page.waitForTimeout(1100);
if(!(await page.locator("#result.active").isVisible()))throw new Error("Win state did not resolve after cameras were disabled");
if(errors.length)throw new Error(`Browser errors: ${errors.join(" | ")}`);
await page.screenshot({path:"tests/smoke.png"});
await browser.close();
console.log("PASS: standalone opened, menu/level select worked, drag/release launched, camera win resolved, and no page errors occurred.");
